name: Push Docker image to ECR
# See ../../aws/push-to-ecr.md for documentation

permissions:
  id-token: write
  contents: read

on:
  workflow_call:
    outputs:
      jobs:
        description: The jobs context as a JSON string.
        value: ${{ toJSON(jobs) }}
    inputs:
      image_name:
        required: false
        type: string
        default: ${{ github.repository }}
      image_tag:
        required: false
        type: string
        default: ${{ github.ref_name }}
      aws_region:
        required: false
        type: string
        default: us-west-2
      cicd_role_arn:
        required: true
        type: string
      directory:
        required: false
        type: string
        default: '.'
      dockerfile:
        required: false
        type: string
        default: Dockerfile
      build_args:
        required: false
        type: string
        default: ''

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ inputs.cicd_role_arn }}
          aws-region: ${{ inputs.aws_region }}
      - name: Login to ECR Registry
        uses: aws-actions/amazon-ecr-login@v1

      # Build and Push Docker Image
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ${{ inputs.directory }}
          file: ${{ inputs.directory }}/${{ inputs.dockerfile }}
          push: true
          cache-from: type=registry,ref=${{ steps.login-ecr.outputs.registry }}/${{ inputs.image_name }}:${{ inputs.image_tag }}
          cache-to: type=inline
          build-args: ${{ inputs.build_args }}
          tags: ${{ steps.login-ecr.outputs.registry }}/${{ inputs.image_name }}:${{ inputs.image_tag }}
