name: Validate Javascript Project
# See ../../npm/validate.md for documentation

on:
  workflow_call:
    outputs:
      install:
        description: The result of the install job.
        value: ${{ jobs.install.result }}
      lint:
        description: The result of the lint job.
        value: ${{ jobs.lint.result }}
      test:
        description: The result of the test job.
        value: ${{ jobs.test.result }}
    inputs:
      directory:
        required: false
        type: string
        default: '.'
      node_version:
        required: false
        type: string
        default: 16.14.2
      install_command:
        required: false
        type: string
        default: 'npm install'
      lint_command:
        required: false
        type: string
        default: 'npm run lint'
      test_command:
        required: false
        type: string
        default: 'npm run test -- --passWithNoTests'
    secrets:
      GITHUB_OAUTH_TOKEN:
        required: false

env:
  CACHE_KEY_NODE: cache-node-modules
  CACHE_KEY_ALL: cache-all

jobs:
  install:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Install Node
        uses: actions/setup-node@v3.4.1
        env:
          GITHUB_OAUTH_TOKEN: ${{ secrets.GITHUB_OAUTH_TOKEN }}
        with:
          node-version: ${{ inputs.node_version }}
      - name: Cache node modules
        id: cache-npm
        uses: actions/cache@v3
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: |
            ~/.npm
            ${{ inputs.directory }}/node_modules
          key: ${{ runner.os }}-build-${{ env.CACHE_KEY_NODE }}-${{ hashFiles('${{ inputs.directory }}/**/package-lock.json') }}
      - name: Install Packages
        run: ${{ inputs.install_command }}
        working-directory: ${{ inputs.directory }}
      - name: Cache service directory
        uses: actions/cache@v3
        with:
          path: |
            ${{ inputs.directory }}
          key: ${{ runner.os }}-build-${{ env.CACHE_KEY_ALL }}-${{ github.run_id }}-${{ github.run_attempt }}


  test:
    runs-on: ubuntu-latest
    needs: [install]

    steps:
      - name: Retrieve service directory
        uses: actions/cache@v3
        with:
          path: |
            ${{ inputs.directory }}
          key: ${{ runner.os }}-build-${{ env.CACHE_KEY_ALL }}-${{ github.run_id }}-${{ github.run_attempt }}
      - name: Install Node
        uses: actions/setup-node@v3.4.1
        with:
          node-version: ${{ inputs.node_version }}
      - run: ${{ inputs.test_command }}
        working-directory: ${{ inputs.directory }}

  lint:
    runs-on: ubuntu-latest
    needs: [install]

    steps:
      - name: Retrieve service directory
        uses: actions/cache@v3
        with:
          path: |
            ${{ inputs.directory }}
          key: ${{ runner.os }}-build-${{ env.CACHE_KEY_ALL }}-${{ github.run_id }}-${{ github.run_attempt }}
      - name: Install Node
        uses: actions/setup-node@v3.4.1
        with:
          node-version: ${{ inputs.node_version }}
      - run: ${{ inputs.lint_command }}
        working-directory: ${{ inputs.directory }}
