name: Test Send Slack Notification

on:
  pull_request:
    paths:
      - .github/workflows/slack-notify.yaml
      - .github/workflows/test-slack-notify.yaml

jobs:
  minimal:
    uses: ./.github/workflows/slack-notify.yaml
    if: success() || failure()
    with:
      channel-ids: U03JNQH43H8
    secrets:
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

  one-line-message:
    uses: ./.github/workflows/slack-notify.yaml
    if: success() || failure()
    with:
      channel-ids: U03JNQH43H8
      project: one-line-message
      message: Bohemian Rhapsody by Queen
    secrets:
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

  multi-line-message:
    uses: ./.github/workflows/slack-notify.yaml
    if: success() || failure()
    with:
      channel-ids: U03JNQH43H8
      project: multi-line-message
      message: |
        I'm just a poor boy from a poor family
        He's just a poor boy from a poor family.
    secrets:
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

  emojis:
    uses: ./.github/workflows/slack-notify.yaml
    if: success() || failure()
    with:
      channel-ids: U03JNQH43H8
      project: emojis
      message: |
        success Success
        failure Failure
        cancelled Cancelled
        skipped Skipped
    secrets:
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
